Dev didier
UFCampos/Discount-Dash pull request #104
Opened 2023-10-10 04:07 UTC by Djoliat

2023-10-10 12:06 UTC, juanpo12 requested changes

2023-10-10 12:06 UTC, juanpo12 commented on components/Orders/Orders.tsx
> +  const id = "6Ks3wWaq8zPnkqGZUhqK"
tenes que cambiar esto y usar el del estado

2023-10-10 12:07 UTC, juanpo12 commented
tiene muchos conflictos, antes hace un pull para resolverlo

2023-10-16 14:48 UTC, juanpo12 approved these changes

2023-10-16 15:59 UTC, juanpo12 approved these changes

2023-10-16 17:44 UTC, thomasrey99 approved these changes

2023-10-16 18:13 UTC, merged